Auth:  refresh token handling and test cases
chanzuckerberg/corpora-data-portal pull request #573
Opened 2020-09-01 21:52 UTC by bmccandless

2020-09-02 17:26 UTC, Bento007 commented on backend/corpora/common/authorizer.py
> +    """ "
I think you have a stray

2020-09-02 17:26 UTC, Bento007 commented on backend/corpora/common/authorizer.py
> +    """ "
```suggestion
    """
```

2020-09-02 17:40 UTC, bmccandless commented on backend/corpora/common/authorizer.py
> +    """ "
fixed

2020-09-02 22:14 UTC, tihuan reviewed
Looks like this is super BE stuff, I don't have much contribution here 😆 LGTM!

2020-09-03 19:15 UTC, Bento007 requested changes
Functionally it looks sounds. Some touch ups are still needed.

Follow ReStructuredText for docstring, for example https://queirozf.com/entries/python-docstrings-reference-examples#restructuredtext-rest. Don't worry about including return type. That will be iin the python typing.

2020-09-03 19:15 UTC, Bento007 commented on tests/unit/backend/chalice/api_server/test_v1_auth.py
> +class TestAuth(unittest.TestCase):
inherit  https://github.com/chanzuckerberg/corpora-data-portal/blob/7eb024c2297255901f053cc9b61a241a2de848b3/tests/unit/backend/chalice/api_server/__init__.py#L8

2020-09-03 19:15 UTC, Bento007 commented on tests/unit/backend/chalice/api_server/test_v1_auth.py
> +        self.app = ChaliceTestHarness(corpora_api_dir)
use https://github.com/chanzuckerberg/corpora-data-portal/blob/7eb024c2297255901f053cc9b61a241a2de848b3/tests/unit/backend/chalice/api_server/__init__.py#L16

2020-09-03 22:21 UTC, bmccandless commented on backend/corpora/common/corpora_config.py
> +    secret keys:
I wasn't sure what you meant.  Was it just to make a json files that looks like the comment here (key and description of the key), then link that file into the readme in that table with other links?

2020-09-03 22:24 UTC, Bento007 commented on backend/corpora/common/corpora_config.py
> +    secret keys:
yes exactly

2020-09-03 22:24 UTC, Bento007 commented on backend/corpora/common/corpora_config.py
> +    secret keys:
otherwise the format for this file will be hidden in the code.

2020-09-03 22:45 UTC, Bento007 approved these changes
LGTM

2020-09-03 22:56 UTC, merged