thuang-850-fix-download-button
chanzuckerberg/corpora-data-portal pull request #852
Opened 2021-01-25 21:30 UTC by tihuan

#850 

#### Reviewers
**Functional:** 
@seve 

**Readability:** 
@MDunitz 

---

## Changes
- add
  - Add selector `hasAssets()` to only enable the Download button if `true`
  - Add new folder and file `frontend/src/common/modules/datasets/selectors.ts `

- modify
  - Disable download button if no asset is available for download

Homepage:
<img width="1407" alt="Screen Shot 2021-01-25 at 1 26 42 PM" src="https://user-images.githubusercontent.com/6309723/105768526-59c38280-5f11-11eb-9839-f97a655b9ece.png">

![demo](https://user-images.githubusercontent.com/6309723/105768588-6ea01600-5f11-11eb-89ef-ac6c87bac2bd.gif)

Collection Page:
![demo](https://user-images.githubusercontent.com/6309723/105768486-503a1a80-5f11-11eb-891b-3c1b9cd44056.gif)

2021-01-25 21:31 UTC, tihuan commented
PTAL all! Thank you!

2021-01-26 19:11 UTC, hthomas-czi requested changes
That looks like the default button style rather than the [disabled button style](https://blueprintjs.com/docs/#core/components/button) to me.

2021-01-26 21:46 UTC, tihuan commented
Ooh!! That's a super great point! Thank you for pointing that out. I could sense that it didn't look right, but I couldn't tell why. Now I know lol

I followed how Blueprint does with disabled primary button and came up with this, does that work? Thank you!

<img width="221" alt="Screen Shot 2021-01-26 at 1 44 48 PM" src="https://user-images.githubusercontent.com/6309723/105909752-d8d1bd00-5fdc-11eb-99d6-f3451ca88828.png">

2021-01-27 00:52 UTC, hthomas-czi approved these changes
Beautiful! 🎉

2021-01-27 00:52 UTC, merged

2021-01-27 04:54 UTC, tihuan commented
Yay! Thanks so much, Harley!!