fix backend unit tests
chanzuckerberg/corpora-data-portal pull request #862
Opened 2021-01-27 21:57 UTC by srm78

1. Fix backend unit tests.
2. Updated make target to run individual test(s). Updated local dev readme on examples of how to run all/some/individual test cases.

2021-01-28 18:27 UTC, mbarrien approved these changes

2021-01-28 22:55 UTC, jgadling approved these changes

2021-01-28 23:54 UTC, Bento007 requested changes
Once change to make

2021-01-28 23:54 UTC, Bento007 commented on tests/unit/backend/corpora/dataset_processing/test_process.py
> +        if os.getenv("BOTO_ENDPOINT_URL"):
Most of this code is duplicated from `setup_s3_bucket`. If this is only used to clean up `setup_s3_bucket`, use [addCleanup](https://docs.python.org/3/library/unittest.html#unittest.TestCase.addCleanup) in `setup_s3_bucket`. Some think like this

```python
def setup_s3_bucket(self, bucket_name):
   ...
   def _delete_s3_bucket(bn):
        bucket = s3.Bucket(bn)
        if bucket.creation_date is not None:
            bucket.objects.all().delete()
            bucket.delete()

   self.addCleanup(_delete_s3_bucket, bucket_name)
   return s3
```

2021-02-01 17:39 UTC, Bento007 approved these changes
LGTM

2021-02-01 18:03 UTC, merged