Dunitz/908 create genesets table
chanzuckerberg/corpora-data-portal pull request #927
Opened 2021-02-23 17:54 UTC by MDunitz

#### Reviewers
**Functional:** 
- @Bento007 

**Readability:** 
 - @seve 

---

## Changes
- add
    - Geneset table and corresponding entity
    - GenesetDatasetLink table and corresponding entity
    - DB migration file
- modify
   - Dataset table to include genesets field (m2m to geneset through GenesetDatasetLink)
   - Collections table to include genesets field (Backref)

## Definition of Done (from ticket)
- Can add a geneset to the database
- Can retrieve a geneset from the database
- Can retrieve a list of all genesets linked to a collection
- Can add a geneset_dataset_link
- Can retrieve a geneset_dataset_link
- Can retrieve all genesets for a dataset
## QA steps (optional)

2021-02-23 19:41 UTC, Bento007 approved these changes
LGTM, fix your link

2021-02-23 19:41 UTC, Bento007 commented on backend/database/README.md
> +- Note: The file is stored under backend/database/file_name but the make command will look in import/file_name this is due to the way [the local paths are mapped to the docker container](3.console.aw
Your link is broken.

2021-02-23 19:44 UTC, MDunitz commented on backend/database/README.md
> +- Note: The file is stored under backend/database/file_name but the make command will look in import/file_name this is due to the way [the local paths are mapped to the docker container](3.console.aw
updated! thanks

2021-02-23 20:09 UTC, Bento007 commented on tests/unit/backend/utils.py
> +import random
If using random make sure you seed it with the current time.

2021-02-23 20:16 UTC, Bento007 commented on tests/unit/backend/utils.py
> +    def generate_random_string(self, length=7):
remove self for static methods

2021-02-23 20:19 UTC, Bento007 requested changes
Since `geneset.name` is not required yet it must be unique, can you have multiple genesets named Null in a collection?

2021-02-23 22:05 UTC, Bento007 commented on backend/corpora/common/corpora_orm.py
> +class DBGenesetDatasetLink(Base, AuditMixin):
change to DbGenesetDatasetLink

2021-02-24 00:24 UTC, seve approved these changes
LGTM

2021-02-24 01:06 UTC, Bento007 approved these changes
LGTM

2021-02-24 01:12 UTC, merged